# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outpatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('main_phone', models.BigIntegerField(null=True)),
                ('alt_phone', models.BigIntegerField(null=True)),
                ('occupation', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('admitted', models.BooleanField(default=False)),
                ('doctors_name', models.CharField(max_length=200)),
                ('doctors_note', models.TextField(null=True)),
                ('appt_date', models.CharField(blank=True, max_length=100, null=True)),
                ('reminder_schedule_1_date', models.CharField(blank=True, max_length=200)),
                ('sign_consent_for_roi', models.BooleanField(default=False)),
                ('reason_for_not_signing_consent', models.CharField(blank=True, max_length=300)),
                ('name_of_center', models.CharField(blank=True, max_length=100)),
                ('patient_received_ed', models.BooleanField(default=False)),
                ('consultation_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_fee', models.IntegerField(blank=True, null=True)),
                ('lab_fee', models.IntegerField(blank=True, null=True)),
                ('medication_1', models.CharField(blank=True, max_length=100)),
                ('medication_2', models.CharField(blank=True, max_length=100)),
                ('medication_3', models.CharField(blank=True, max_length=100)),
                ('medication_4', models.CharField(blank=True, max_length=100)),
                ('medication_5', models.CharField(blank=True, max_length=100)),
                ('medication_6', models.CharField(blank=True, max_length=100)),
                ('medication_7', models.CharField(blank=True, max_length=100)),
                ('message_sent', models.TextField(blank=True)),
                ('contacted_patient', models.BooleanField(default=False)),
                ('patient_showed_up', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('has_all_medications', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('issues_with_taking_medication', models.BooleanField(default=False)),
                ('reminder_frequency', models.CharField(blank=True, max_length=300)),
                ('reminder_end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
    ]
