# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name_plural': 'allergies'},
        ),
        migrations.AlterModelOptions(
            name='appointmentreminder',
            options={'verbose_name_plural': 'Appointment Reminders'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'verbose_name_plural': 'certifications'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='diagnosiscategories',
            options={'verbose_name_plural': 'Diagnosis Categories'},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'verbose_name_plural': 'Emergency Contacts'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'facilities'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='medicationcategory',
            options={'verbose_name_plural': 'Medication Categories'},
        ),
        migrations.AlterModelOptions(
            name='medicationreminder',
            options={'verbose_name_plural': 'Medication Reminders'},
        ),
        migrations.AlterModelOptions(
            name='prescribedmed',
            options={'verbose_name_plural': 'Prescribed Medications'},
        ),
        migrations.AlterModelOptions(
            name='quarter',
            options={'verbose_name_plural': 'quarters'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'specialties'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name_plural': 'Visits'},
        ),
    ]
