# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='main_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
