# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0002_auto_20170811_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
