# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 02:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatient',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='outpatient',
            name='surname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\s]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
