# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0003_auto_20170811_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='diagnosiscategories',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='medicationcategory',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='quarter',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='description',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(unique_for_date=True),
        ),
    ]
