# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0003_auto_20170812_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='outpatient',
        ),
    ]
