# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0004_auto_20170811_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatient',
            name='reason_for_not_signing_consent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
