# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outpatients', '0005_auto_20170812_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationreminder',
            name='pcc',
        ),
        migrations.AddField(
            model_name='medicationreminder',
            name='pcc',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
