# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0007_auto_20170811_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(unique_for_date=True),
        ),
    ]
