# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatients', '0008_auto_20170811_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(),
        ),
    ]
