RELATIONSHIP_CHOICES = (
    ('Sib', 'Sibling'),
    ('M', 'Mother'),
    ('F', 'Father'),
    ('C', 'Cousin'),
    ('F', 'Friend'),
    ('D', 'Daughter'),
    ('S', 'Son'),
)

ROUTES_CHOICES = (
    ('AAA', 'AAA (Apply to Affected Area)'),
    ('AD', 'AD (Right ear)'),
    ('AS', 'AS (Left ear)'),
    ('AU', 'AU (Each ear)'),
    ('IJ', 'IJ (Injection)'),
    ('IM', 'IM (Intramuscular)'),
    ('IN', 'IN (Intranasal)'),
    ('INJ', 'INJ (Injection)'),
    ('IV', 'IV (Intravenous)'),
    ('NPO', 'NPO (Nothing By Mouth)'),
    ('OD', 'OD (right ear)'),
    ('OS', 'PO (left ear)'),
    ('OU', 'OU (both eyes)'),
    ('PO', 'PO (orally or by mouth)'),
    ('PR', 'PR (rectum)'),
    ('PV', 'PV (vagina)'),
    ('SL', 'SL (Sublingual)'),
    ('TOP', 'TOP (topical)'),
)

FREQUENCY_CHOICES = (
    ('ac', 'ac (before meals)'),
    ('achs', 'achs (before meals and at bedtime)'),
    ('alt. h.', 'alt. h. (every other hour)'),
    ('ap', 'ap (before dinner)'),
    ('ATC', 'ATC (around the clock)'),
    ('BID', 'BID (twice a day)'),
    ('n', 'n (in the night)'),
    ('noct. maneq.', 'noct. maneq. (night and morning)'),
    ('o.d', 'o.d. (once per day)'),
    ('prn', 'prn (as needed)'),
    ('pc', 'pc (after meals)'),
    ('q12h', 'q12h (every 12 hours)'),
    ('qd', 'qd (daily)'),
    ('q2h', 'q2h (every 2 hours)'),
    ('q3h', 'q3h (every 3 hours)'),
    ('q4h', 'q4h (every 4 hours)'),
    ('q6h', 'q6h (every 6 hours)'),
    ('q6PM', 'q6PM (every evening at 6pm)'),
    ('q8h', 'q8h (every 8 hours)'),
    ('qam', 'qam (every morning)'),
    ('QD', 'QD (every day)'),
    ('qh', 'qh (every hour)'),
    ('qhs', 'qhs (every night at bedtime)'),
    ('qid', 'qid (four times a day)'),
    ('qod', 'qod (every other day)'),
    ('TID', 'TID (three times a day)'),
    ('tid ac', 'tid ac (three times a day before meals)'),
    ('TIN', 'TIN (three times a night)'),
    ('TIW', 'TIW (three times a week)')
)
